#!/bin/bash

#Custermize this for your application
APPLICATION_FILE_PATH=start-femr

#Parameters
PRODUCT_HOME=/Library/__PRODUCT__/__VERSION__

echo "Post installation process started"

#Change permissions in home directory
echo "Change permissions in product home"
cd ${PRODUCT_HOME}
chmod -R 755 .
[ -d /usr/local/bin ] || mkdir /usr/local/bin

#Add application shortcut to /usr/local/bin
rm -f /usr/local/bin/__PRODUCT__-__VERSION__
cp -R ${PRODUCT_HOME}/${APPLICATION_FILE_PATH} /Applications/fEMR
echo "Post installation process finished"

#mv to /var
rm -rf /var/__PRODUCT__/
mv -f $PRODUCT_HOME /var/__PRODUCT__/


